set(TIZEN_SDK_DIR $ENV{TIZEN_SDK_DIR})
if(NOT DEFINED TIZEN_SDK_DIR)
  message(FATAL_ERROR "Tizen SDK dir is not set")
endif()

set(TIZEN TRUE)
set(TIZEN_SDK_VERSION 2.3)
set(TIZEN_SDK_VERSION_MACRO 230)

if(DEFINED ENV{TIZEN_EMULATOR_BUILD})
  set(TIZEN_TARGET i686-linux-gnueabi)
  set(CMAKE_SYSROOT "${TIZEN_SDK_DIR}/platforms/tizen-${TIZEN_SDK_VERSION}/mobile/rootstraps/mobile-${TIZEN_SDK_VERSION}-emulator.core")
  set(TIZEN_TOOLCHAIN_DIR "/home/crossi386")
  set(CMAKE_FIND_ROOT_PATH ${TIZEN_TOOLCHAIN_DIR} ${CMAKE_SYSROOT}/usr)
else()
  set(TIZEN_TARGET arm-linux-gnueabi)
  set(CMAKE_SYSROOT "${TIZEN_SDK_DIR}/platforms/tizen-${TIZEN_SDK_VERSION}/mobile/rootstraps/mobile-${TIZEN_SDK_VERSION}-device.core")
  set(TIZEN_TOOLCHAIN_DIR "/home/cross")
  set(CMAKE_FIND_ROOT_PATH ${TIZEN_TOOLCHAIN_DIR} ${CMAKE_SYSROOT}/usr)
endif()


set(CMAKE_SYSTEM_NAME    Generic)
set(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_C_COMPILER   "${TIZEN_TOOLCHAIN_DIR}/bin/${TIZEN_TARGET}-gcc")
set(CMAKE_CXX_COMPILER   "${TIZEN_TOOLCHAIN_DIR}/bin/${TIZEN_TARGET}-g++")
set(CMAKE_AR "${TIZEN_TOOLCHAIN_DIR}/bin/${TIZEN_TARGET}-ar")
set(CMAKE_RANLIB "${TIZEN_TOOLCHAIN_DIR}/bin/${TIZEN_TARGET}-ranlib")

set(CMAKE_C_FLAGS "-fPIE ${CMAKE_C_FLAGS} -DTIZEN_SDK_VERSION=${TIZEN_SDK_VERSION_MACRO}" CACHE STRING "")
set(CMAKE_CXX_FLAGS "-fPIE ${CMAKE_CXX_FLAGS} -DTIZEN_SDK_VERSION=${TIZEN_SDK_VERSION_MACRO}" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS "-static-libstdc++ -pie -Wl,--as-needed -Wl,--no-undefined ${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "")


set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
